apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: no-reply@52poke.net
    privateKeySecretRef:
      name: le-cloudflare-issuer
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-dns
            key: token
