apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-52w-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hcloud-volumes