apiVersion: v1
stringData:
    block.yaml: ENC[AES256_GCM,data:Am/dn6JxcrxeT3QsbGtsNpRnlxP18f/p35A5g+xLjSxAcDd3oVLGeZCiowS2vmw+M/nEfUA8MWci8/kEOozFyreYABfczmUe7Y/9pmtHIQAsmT9G4e562ly/aiPK82MPBOkgo9lXeC3WF9lz89CUdkykq6JwwyPhCWZcjFX67eOtq/1egyNsS4Fr7jobndZnzOtu+hgkqmzBmuxpTwF6W3WhTxsRbc6NQ8hTmX1Zk1SBJV3MD78RkIcEQIKBPPipDSbsZ8pbG27gcMGDuPJc5xed4pcBOzyqNS/ad+MAxRDms3YUBIX9StVUqDsJbJkc7kFAXR75ZuJqkLKxDNMD8s0PaUulwVUSB7sWRl8+L3vbCQzx6+vXnObanxkzoy6c5pmsdod8JPmtFvdQJOnHzZu6ISWnFZ7AMZeIMMfhnnnAk+e2rTmoS5vSd9aASiH3w4LnbwLHujP4EeezeclvLTfjq6sNDBGbDbJ8TDTay9cylL/aa/Rd2/6RQnCbrmGBbh1BDjMrjv9vu9jnwg4ocwIw3zCX8eORlDIWshGwzAKiPnepDWGrgeCZe64W9Iu2Mdbtn3oXHID6Sl4qqri8wcv8i/r4JotS2biqAfJlSe+cVGKj4IKMiMREQAFf2ze/mMcG0Dd2rybafbWJydNMCDIp8WvhX6tA5bUq7BZvNYT0P6OzQu92/DdUINT9cN9YeH8emjysSf0HTB5tj9RpGEZm+8JIR64TtlIhxVvT1g11bENKiQN4U9ndFE4ERN7N306kQyN+jRWmy6q7ysEEbrNiL+3OKiJY4husQXqaoZAZtNXjyKlMDOqzDmTPhpn0kBzym27CHwivU8FYWC1Jvng/ar1NMYN6ONSBYmPZi45RQJyPL4QB3lPtyvKuHn/rkax7NVimCHh1fHr3gAxWAAQBA//4sCHmwdd7oCrHddDh0fqz4WKksJf74aKTXjZWdCJNgqjzJU34I56zrdPcDnKtpCUDubXhfSUtn5gWZS6Yin/A4Sw1HGMjLOfp/KdG/B4xRYO2fBgTzUFdmaHz6h+90haFZAoc97gxmaUnuoKceJ0riXxYc0qaNcKMEq168M4ZwjLRVcmLSG29RY5djh7LYv96jaMZJnd8tQx15ffjoGhWjfJGtIimhzfRm07/mgFjEehv4/+6tqFO2Jl13ddmWocRj10eYqetIcu0/br1pVuN4rtAcXxomOP78rqy9hBoFmhfYSR10PfnkCimHbMOS8jHPGHGtUViPw3Y6ZoT46hcXq9VRnaR7yvHOtlDFl+A,iv:KmY3oZZHmTUKLhR27i+PRHgvxEYV+IT/1/NeyErLnC4=,tag:VF0FjiIU+MPHTStbjpTYMQ==,type:str]
kind: Secret
metadata:
    name: nginx-52w
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVzBZN3ZaQ0FYYnJxMktV
            RDJUUDQ5SFV2eE5JM3MrVktscVdMR0FJbGhrCmJ1YlM0cVpkeDVrK1lEKzNnWFNp
            VmJsVXlWZ0RpWGFOUTc3VTNBVXZxTmcKLS0tIEovOVhOdklDOHlOVitGcGpGNUt0
            VFl6Y1lHR05wTytWTGY2WlU5SkJLbTAKlFY4hpwF8IJ7ioTiqLNGAtPiXoM13+Ot
            ey6aTV+ZQ0dDlnniAGO6CsrUszYYMSQn9jsP0rFIAKzkh8TfsrQfTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T15:01:22Z"
    mac: ENC[AES256_GCM,data:O6ShALOFgjME3A8sKnP+hTZNNXwEoBiI9NJDvSWOny3fQrAmnH1RWaVSFd4RRyCEJcjsjka3w33ud7jGWKuwY7K6wfoepelKVXZslK5Hp6x9AdesZuDPh9QrwwiN0TLXwj/xLNXAHtf0+ue+Cu0z64wt2g89eEuEuH5uhda6KUk=,iv:VZP5h+DwfE1zzEqzgy36cV9dsn+xednnnkvNhJtEi1E=,tag:G9Xyf3vbADtIMWQm6ZKY/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.9.1
