apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-csi
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: hcloud-csi
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system