apiVersion: batch/v1
kind: Job
metadata:
  name: mediawiki-update
  namespace: default
spec:
  #suspend: true
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers:
      - image: ghcr.io/52poke/mediawiki:latest
        imagePullPolicy: Always
        command:
        - "/bin/sh"
        - "-c"
        - |
          set -e
          echo '' > /home/52poke/wiki/extensions/Echo/sql/mysql/patch-echo_push_subscription-drop-foreign-keys_2.sql
          cd /home/52poke/wiki/maintenance
          php update.php
        name: 52poke-wiki
        resources:
          requests:
            cpu: 400m
            memory: 384Mi
        volumeMounts:
        - mountPath: /home/52poke/wiki/LocalSettings.php
          name: 52poke-wiki-config
          readOnly: true
          subPath: LocalSettings.php
        - mountPath: /run/secrets/52w-db-user
          name: mysql-user
          readOnly: true
          subPath: username
        - mountPath: /run/secrets/52w-db-password
          name: mysql-user
          readOnly: true
          subPath: password
        - mountPath: /run/secrets/52w-secret-key
          name: 52poke-wiki-secret
          readOnly: true
          subPath: secretKey
        - mountPath: /run/secrets/52w-upgrade-key
          name: 52poke-wiki-secret
          readOnly: true
          subPath: upgradeKey
        - mountPath: /run/secrets/aws-s3-ak
          name: aws-s3
          readOnly: true
          subPath: accessKeyID
        - mountPath: /run/secrets/aws-s3-sk
          name: aws-s3
          readOnly: true
          subPath: secretAccessKey
        - mountPath: /run/secrets/aws-smtp-ak
          name: aws-ses
          readOnly: true
          subPath: accessKeyID
        - mountPath: /run/secrets/aws-smtp-sk
          name: aws-ses
          readOnly: true
          subPath: secretAccessKey
        - mountPath: /run/secrets/recaptcha-site-key
          name: recaptcha
          readOnly: true
          subPath: siteKey
        - mountPath: /run/secrets/recaptcha-secret-key
          name: recaptcha
          readOnly: true
          subPath: secretKey
        - mountPath: /run/secrets/oauth2
          name: 52poke-wiki-oauth2
          readOnly: true
      restartPolicy: Never
      volumes:
      - configMap:
          name: 52poke-wiki-1-43
        name: 52poke-wiki-config
      - name: mysql-user
        secret:
          secretName: mysql-wiki
      - name: 52poke-wiki-secret
        secret:
          secretName: 52poke-wiki
      - name: 52poke-wiki-oauth2
        secret:
          secretName: 52poke-wiki-oauth2
      - name: aws-s3
        secret:
          secretName: linode-object-storage
      - name: aws-ses
        secret:
          secretName: aws-ses
      - name: recaptcha
        secret:
          secretName: recaptcha
