apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-cache-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes