apiVersion: v1
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:zSAIzIcslgf/m/eN2YhqsgA6SHXKyuNDHApKGd0HiCSGulPs1lyGXz6Dr5GD6/NJc7MI7q8VPUG0Rxf0L+Xm3btmko5hDlegrA8mU/uGEcukdrxcDOZBK2G5voWJ,iv:FPw04F/T2xvPLB2Bak2XuJoNOUn6a/OxWXuMfwcI8ww=,tag:zS4JmEc5erFLa3DLZ4o+GQ==,type:str]
    RELEASE_ZIP_PASSWORD: ENC[AES256_GCM,data:Em/9YMdAAdWwlw==,iv:zHRiytAIT2imajBlYGUACVxQz+3PKnhepbF93FVT8NM=,tag:RS/QVo9MoQta2VQqwcAtIg==,type:str]
kind: Secret
metadata:
    name: mwarchiver
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS1EyQWtWUnM5ektLTnlU
            RHRiZlJNL3pxaGtiOW0wZlMybjFBNUh6bHhRCmtkcXpURHpJOVM1ZkNlcklFaXV2
            RFlIdXdiRklBY1FSNkgzeTVBYTFLeTAKLS0tIE1lc0krNDZUN0VLUzdvQkxhUzBM
            NHhQLzBmVUNMU2JPa0k4a1grWDY2c3cK1SlLNsrCb5JyaSPwK1oQVzE9IdaOfYMc
            U6G0QrMTaSMEUWuq6xWldxysJdqfDgxgPekiWuDndNAQkBcCZgAY6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T09:20:45Z"
    mac: ENC[AES256_GCM,data:A1x9PYbUIvx02TgAbNYtOfrVYnLfNHuwn3yi8MGon9feZWiwYjeoZgn6myBpPa1HyjsDhn7FtG86TULOdrW1lpwt3oR9iUtFKEUMfoW1kiR9YJc0thr+xc5Pho1EdpXFff1KA+z/PJwaRG+9xSmQiSAbRvJ4uB/4Xsy1+jNFPu0=,iv:/2eyyZp5dDRyZ9Jz6CPAu7WhoOZ3SQpJYIZJiVj5/uk=,tag:2QiQ235R2Mpcj8NDsepDpQ==,type:str]
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.11.0
