apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:YqgdySFGgbIxQb/lorFotfHNLRJN4+gAc2wuGUMUa428chcM47EUMyqPO/i1JhI3H5baXWESURi/SjazMT+sXA==,iv:eciPk6aTzHrRARTiY5FUsvqpfg1G7Deb9Aip8FD5LRs=,tag:yT5ZZXaCH/+7kwYWrQvToA==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OWNNWVhXSGlnMXhGR0VL
            ZC85Zlp0U2pjdm1VY0xoVEVRNUdpWEJ3TUVVCkZRWXJwLy9EYVlpaHdtR3pLN2pu
            V2tnZzZxYTdEYnphOHJ6Y0ttRDdBWHcKLS0tIDJpRkhmbVhUSGRBcVlLeVNYY25L
            aFI0L3B3bzQycGtiR2RJeWJoMmNjcXMKvr8yfSD4ahKid4c1kwiLrTxNZEAgYMKa
            qBmP/01oErLtHb9wakEtNtL1vq/4TKo/uuYInCFnluqI91rZaxO9MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T11:10:43Z"
    mac: ENC[AES256_GCM,data:evv0sQYTC3437v/skuN1IIWLGyFWGmmsHfgWAPJwAV1gE+LZWezAGSh3+7K2bFaG8qZHyD39ntUmfHcQDzF7/AMw4JWrM/vO9js19KIrlhiJOYrVS78gqodGi6VfM2iSdWZjswVRaXpOEXSXzmYzwuxhl28GGjrPOB6+TY7mcSs=,iv:TEH1kOKxLDh/IAfn/WDly2HiR3iwTp61IELCn9XawU4=,tag:L6DItpWKkFWHylaJsvFjQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.9.1
