apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx640m -Xms640m
        - name: discovery.type
          value: single-node
        image: ghcr.io/52poke/52w-elasticsearch:latest
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: es
        - containerPort: 9300
          name: es-control
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            cpu: 200m
            memory: 1280Mi
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-persistent-storage
          subPath: data
      securityContext:
        fsGroup: 1000
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pvc