apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      config:
        log-format-escape-json: "true"
        log-format-upstream: '{"timestamp": "$time_iso8601", "remote_addr": "$remote_addr", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}'
        forwarded-for-header: CF-Connecting-IP
        use-forwarded-headers: "true"
      replicaCount: 1
      service:
        type: NodePort
  valuesFrom:
  - kind: Secret
    name: nginx-node-ports
    valuesKey: httpPort
    targetPath: controller.service.nodePorts.http
  - kind: Secret
    name: nginx-node-ports
    valuesKey: httpsPort
    targetPath: controller.service.nodePorts.https