apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-52poke-www
  namespace: default
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
