apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: 52poke-www-config
  files:
  - "nginx.conf=nginx.conf"
  - "php-custom.ini=php-custom.ini"