apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:8wQ1dK4wok7cOBpKmV+RlsoibTom3F8HAF6NspytGsQm7VjKTe/MfM+n1ufbai9W,iv:BHrgDwT/ooQ50ofFgAws7PlCMO+Z4IWXmUXXtrmWqDI=,tag:Ldy4al4iQni49qqlB14HAA==,type:str]
    wiki-oauth-key: ENC[AES256_GCM,data:yg4LJmX0nD3gIjwviFzUmKOWT5zo2HQJYACBBUUwv5Z1WwLmc7BcvV547rk=,iv:bqJUy+NtZQIivHTcPTAmXQDOE5MYXqlNtfLVMI9yG3M=,tag:uaA8CVsgqjpLN5AnZaMOXw==,type:str]
    wiki-oauth-secret: ENC[AES256_GCM,data:g3x4xsBkHgHZ5aqkCQFjBzkFCaVZLjq9JRqy051hAswFqOMIKA1RaKLOtN18MLFfFhy3MlUSsJw=,iv:xmJ5w1uXOz8hlWWuiAb5FLVjcqWQ5VuK/NBTgSDIaWg=,tag:gVXwRQtvfCn/2sZrCeWAvA==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:LY9iOvMA6tMEpsXb/pyi1W+hLschvHBuT9Lg7rTXcBQOXXTyHeWGvcXBDg0CSFPaD40xp2y9gnIcy5Q7Gcp18sHf3uluLkI5BYe3h25ctfdtt5lYthQeyrLrxIJ9XqIXcSrUkw==,iv:+Ysvq38nKmVmfPaG1R82l0tdd5X0IYbBdt1w90Jkn7c=,tag:GnIbcEojyEw4i/bnITuZfQ==,type:str]
kind: Secret
metadata:
    name: klinklang
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZnRBdm8yUEVYWk1uMTJY
            R29RdFdJRG51YlVNYmtUb2ZrS1B3RWljTVNjCm5SU2RxRXZwZ1YrVTNFTDZKK2d0
            K2ZNcUc4V1BieTc5RWJINkpITWJnQU0KLS0tIDBsMXhXeGZHSEhsVmVyRVBmVXVQ
            clk3WDlVdldvWVRjNE8rUjBTM0lqREUKstQ4CugsU2/67fWgSXM33QV6/qmOPjAG
            inTP0Q3ZrXvHfb9X6LD4KFUKGRox143UUavtOiM+7iXKD+8QTkTi7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T15:59:25Z"
    mac: ENC[AES256_GCM,data:Yy9YE/+rWh0l9j8U550hNGRAyaN9jUZvPBjvvdmwsamso4ZXnJehOnw92m/H5F5VERuKYV6BtfzBpmfw4TkARxx3gv1/W7s7pIXYuWSZhirtXMewhZVNuQGgSmDvLK0c3RR+sk1iZBEg3ytZfK0M565IZY6btarWxuXZMrxBK+M=,iv:mdvkSQizFMES273fGAz/TR27iBszyTHiC/fDLvhjZEA=,tag:WujPOKSuRDIN8YQnhdxcQQ==,type:str]
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.11.0
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:iRerSh4QZFppvU8iNqc+mVhluHL9JMb2,iv:nTwhu9nxrVZJUXyz94Szjpj9r4YSGPNaODgOrQ/IiBQ=,tag:GzR+CKaj/uOL7SIlZhE7yA==,type:str]
    url: ENC[AES256_GCM,data:F2wCongx/TOR3XRhogqbxWYRsTTHw8qNWO/MxqDxPqI48i3+Vi1eoVSlC+4HW3JQ3SrWMF8StphR4bSrklqffgqVTPAcMDItYk6SMTv67rbWzN3uPHCdDtuZ3GhrxADU,iv:DFsoCfRuVg4Dqjyq/sBeA62HPNFLZ8sI3jv/wt4bcNw=,tag:+Xu/yqsmi0ghZjqIYWSheg==,type:str]
    username: ENC[AES256_GCM,data:DJXgPNhO0FHPYjMN,iv:BXw6y56NKiLArkLs9bbnMD7W1Ei+8Lyvl7hDc5+ZsoY=,tag:2g0W2HOpheS7UjhsZsaIsQ==,type:str]
kind: Secret
metadata:
    name: postgres-klinklang
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZnRBdm8yUEVYWk1uMTJY
            R29RdFdJRG51YlVNYmtUb2ZrS1B3RWljTVNjCm5SU2RxRXZwZ1YrVTNFTDZKK2d0
            K2ZNcUc4V1BieTc5RWJINkpITWJnQU0KLS0tIDBsMXhXeGZHSEhsVmVyRVBmVXVQ
            clk3WDlVdldvWVRjNE8rUjBTM0lqREUKstQ4CugsU2/67fWgSXM33QV6/qmOPjAG
            inTP0Q3ZrXvHfb9X6LD4KFUKGRox143UUavtOiM+7iXKD+8QTkTi7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T15:59:25Z"
    mac: ENC[AES256_GCM,data:Yy9YE/+rWh0l9j8U550hNGRAyaN9jUZvPBjvvdmwsamso4ZXnJehOnw92m/H5F5VERuKYV6BtfzBpmfw4TkARxx3gv1/W7s7pIXYuWSZhirtXMewhZVNuQGgSmDvLK0c3RR+sk1iZBEg3ytZfK0M565IZY6btarWxuXZMrxBK+M=,iv:mdvkSQizFMES273fGAz/TR27iBszyTHiC/fDLvhjZEA=,tag:WujPOKSuRDIN8YQnhdxcQQ==,type:str]
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.11.0
