apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: nginx-media
  files:
  - "nginx.conf.tmpl=nginx.conf.tmpl"