apiVersion: v1
data:
    secretKey: ENC[AES256_GCM,data:96FPtwu8iV4EvuLOvfanx2/ue95L4aAV+8eD6u4o54PzXrZZbXjSCX6Dxmp1kmg6jL9Ji1Md25A=,iv:aoD//HwEG6RStB5h3igZ6azXHwDpkGG0hzVzdR+7HUk=,tag:ET1twLBQGrNjuYEsWr9jrA==,type:str]
    siteKey: ENC[AES256_GCM,data:Ez/kIBdttW9Wyxqg1Gs0wkunQMKCKmSJ2evO7HF5KgRCHM23iwMm1LEgUou8ZYOJU9AMBlbwK8Q=,iv:HJdNf1uw/md6j1uGTB6hExOmyfissCvvPo6qr9DCFOI=,tag:/kPbMKQe6A5PIPwa0/iOoQ==,type:str]
kind: Secret
metadata:
    name: recaptcha
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRE0vanArdVo3d2VjR2dv
            b2duTVpFd1ZoOWZvKy9RTGtDbDJRakdwd3hBCkIyOVZXSWJMZ25aMDBHU3cvNkZT
            Q1JNS0ZINUFMWms4NGRnQmNNOWdsU0kKLS0tIGlUakxJb01HRmJOU3dzcFNSQkFj
            RVRlL0Vrb2hVemw0QmJyTzF3QW5UMEkK7tKksa5JOd2jm/D/CsFljUFkiExOQUGy
            yQ26ZwLCL0r7VM53HXVw27bojKuX4L/tEp/WnSP45geiWklp31esJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T11:42:03Z"
    mac: ENC[AES256_GCM,data:bj3STE3XxBs3dB2dFjdyG0gzJm7eG67dxcSivL25uXNidxe2doq4s9WzC9TbizcxrsHaYJO/JU0Jfx/zH1NheZuAJIsfKBcdhtIxp2EtnuCSX7kk7AcyYdP/121fEV4+m68DGk7JfI9XCt3C520OwgKlBmQ84aKFd+e5I9odKWc=,iv:ZAGGee4e3rKjC++xMLImVg9GTDbQ0nxGwh4RrUmltqo=,tag:uEJn6DP0O5WUcYYRqvxNQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.7.3
