apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-restore
  namespace: default
spec:
  ttlSecondsAfterFinished: 180
  suspend: true
  template:
    spec:
      containers:
      - name: mariadb-restore
        image: mariadb:11.4
        command:
        - /bin/sh
        - -c
        - |
          set -e
          apt-get update && apt-get install -y zip curl man-db
          curl https://rclone.org/install.sh | bash

          echo '[client]' > /root/.my.cnf
          echo 'user=root' >> /root/.my.cnf
          echo "password=$MYSQL_ROOT_PASSWORD" >> /root/.my.cnf

          # Drop existing tables
          echo "SET FOREIGN_KEY_CHECKS = 0;" $(mariadb-dump -h mariadb --add-drop-table --no-data 52poke | grep 'DROP TABLE') "SET FOREIGN_KEY_CHECKS = 1;" | mariadb -h mariadb 52poke
          echo "SET FOREIGN_KEY_CHECKS = 0;" $(mariadb-dump -h mariadb --add-drop-table --no-data makeawish | grep 'DROP TABLE') "SET FOREIGN_KEY_CHECKS = 1;" | mariadb -h mariadb makeawish

          # Download and restore from backup
          mkdir -p /tmp/mysql-restore
          cd /tmp/mysql-restore
          rclone copy b2:52poke-backup/database/52poke.sql.gz .
          (echo "SET SESSION SQL_LOG_BIN=0;"; gzip -dc 52poke.sql.gz) | mariadb -h mariadb 52poke
          rclone copy b2:52poke-backup/database/makeawish.sql.gz .
          (echo "SET SESSION SQL_LOG_BIN=0;"; gzip -dc makeawish.sql.gz) | mariadb -h mariadb makeawish
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root
              key: password
        - name: RCLONE_CONFIG_B2_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: backblaze-b2
              key: b2-account-id
        - name: RCLONE_CONFIG_B2_KEY
          valueFrom:
            secretKeyRef:
              name: backblaze-b2
              key: b2-account-key
        - name: RCLONE_CONFIG_B2_TYPE
          value: b2
      restartPolicy: Never
